FROM ghcr.io/rocker-org/devcontainer/tidyverse:4.5

# RUN \
#   echo 'options(repos=c(CRAN="https://packagemanager.posit.co/cran/__linux__/bookworm/latest"))' >> ~/.Rprofile && \
#   Rscript --vanilla -e 'getOption("repos")'

# Installing pdflatex via tinytex
# RUN install2.r --error tinytex && Rscript --vanilla -e "tinytex::install_tinytex()" && \
#   cat "export PATH=/root/bin:$PATH" >> /root/.bashrc && \
#   apt-get update && apt-get install --no-install-recommends -y tidy

RUN apt-get update && apt-get install --no-install-recommends -y valgrind gdb \
  libglpk-dev

RUN apt-get update && apt-get install --no-install-recommends -y pre-commit nano

RUN install2.r --error languageserver && \
installGithub.r nx10/httpgd

# Adding R packages
RUN install2.r --error cpp11 roxygen2 testthat data.table dplyr \
  devtools patchwork quarto torch

RUN installGithub.r UofUEpiBio/epiworldR@main


CMD ["bash"]
